INHERIT: mkdocs-base.yaml

site_name: "Dynatrace Enablement Lab: dtwiz 101"
repo_name: "View Code on GitHub"
repo_url: "https://github.com/dynatrace-wwse/enablement-dtwiz-101"
nav:
  - "Welcome": index.md
  - "00. Getting Started": 00-getting-started.md
  - "01. Install dtwiz": 01-install-dtwiz.md
  - "02. Connect & Analyze": 02-connect-and-analyze.md
  - "03. Deploy the Demo App": 03-install-demo.md
  - "04. Recommend & Watch": 04-recommend-and-watch.md
  - "Resources": resources.md
  - "Cleanup": cleanup.md

extra_javascript:
  - javascripts/assessment-gate.js

extra:
  rum_snippet: "https://js-cdn.dynatrace.com/jstag/1612cf70810/bf81393wlb/7c50bce5c0cc890f_complete.js"
